steps:
  - name: 'maven:3.8.4-openjdk-17'
    entrypoint: 'mvn'
    args: [ 'install' ]
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - 'JAR_FILE=target/*.jar'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME:$COMMIT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME:$COMMIT_SHA'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION
      - '--port'
      - '8080'
    entrypoint: gcloud
timeout: 1200s
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME:$COMMIT_SHA'